### PR TITLE
Fixes an issue where song sort order is 0 when adding to playlist

### PR DESCRIPTION
**Pull request by timusus**
This chang ensures that the sort order for a song added to a playlist starts at a minimum value of playlist.songCount. This prevents multiple entries with a sort order of '0' which can cause the true sort order to be lost.

### CODE REVIEW

**Comment by timusus** [comment]
Supersedes #118, fixes #117

**Comment by daladim** [comment]
Thanks for this MR! Probably more efficient than #118 indeed :)

I haven't tested it yet (but I suppose you did, so that's fine for me!)

**Comment by timusus** [comment]
@daladim I actually haven't tested this 😳

**Comment by daladim** [comment]
I've just successfully tested it, I think this can be safely merged into `main`. Thanks!

**Pull request merged**
